// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozntdahkxxolimpjocgk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96bnRkYWhreHhvbGltcGpvY2drIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1ODM0MTcsImV4cCI6MjA3MjE1OTQxN30.VHbsP8vUT9AQT7Ipjd9T43-_Hoh4mrNzt4aYG5C3Jp4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});